######################################################################
# Automatically generated by qmake (2.01a) Sun Sep 22 13:46:39 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += keytest.h
FORMS += keytest.ui
SOURCES += keytest.cpp main.cpp
