######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 26 13:59:17 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h myinputpanel.h myinputpanelcontext.h
FORMS += mainwindow.ui myinputpanelform.ui
SOURCES += main.cpp \
           mainwindow.cpp \
           myinputpanel.cpp \
           myinputpanelcontext.cpp
