######################################################################
# Automatically generated by qmake (2.01a) Mon Dec 2 22:51:59 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h myinputpanel.h myinputpanelcontext.h
FORMS += mainwindow.ui myinputpanelform.ui
SOURCES += main.cpp mainwindow.cpp myinputpanel.cpp myinputpanelcontext.cpp
