######################################################################
# Automatically generated by qmake (2.01a) Thu Sep 26 15:37:29 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gprs.h myinputpanel.h myinputpanelcontext.h
FORMS += gprs.ui myinputpanelform.ui
SOURCES += gprs.cpp main.cpp myinputpanel.cpp myinputpanelcontext.cpp
