#!/bin/sh
#
# Start mdev 
#

start() {
	printf "Starting mdev: "
	echo /sbin/mdev > /proc/sys/kernel/hotplug
	mdev -s
	echo "OK"
}

stop() {
	printf "Stopping mdev: "
	echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
